### ISSUE TITLE
Deleting a 'watched' file errors the watch process

### ISSUE THREAD

**Issue by benjamin-asdf** [squint-cljs/squint#475]
**version**

0.6.89

squint watch. 
- Add a cljs file in the dir you watch
- Delete file

You get such a thing 

node:internal/fs/utils:350
    throw err;
    ^

Error: ENOENT: no such file or directory, lstat 'src/InfoIconWithTooltip.cljs'
    at Module.lstatSync (node:fs:1668:3)
    at FSWatcher.<anonymous> (file:///home/benj/repos/mysentientai-website/node_modules/.pnpm/squint-cljs@0.6.89/node_modules/squint-cljs/lib/cli.js:46:115)
    at FSWatcher.emit (node:events:517:28)
    at /home/benj/repos/mysentientai-website/node_modules/.pnpm/chokidar@3.6.0/node_modules/chokidar/index.js:582:16
    at Map.forEach (<anonymous>)
    at Timeout._onTimeout (/home/benj/repos/mysentientai-website/node_modules/.pnpm/chokidar@3.6.0/node_modules/chokidar/index.js:580:30)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7) {
  errno: -2,
  syscall: 'lstat',
  code: 'ENOENT',
  path: 'src/InfoIconWithTooltip.cljs'
}

watch process terminates. 

doesn't matter for really but maybe somebody might consider it a bug.

**Comment by borkdude** [comment]
Thanks. Will look at this next week.
